version: "3.9"
services:
  vault:
    build:
      context: .
      dockerfile: docker/plugin.Dockerfile
    env_file:
      - .env.plugin
    volumes:
     - ./plugin:/app/plugin
  vault-server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    ports:
      - 8000:8000
      # Uncomment if custom VAULT_WEB_PORT needs to be used.
      # - $VAULT_WEB_PORT:$VAULT_WEB_PORT
    volumes:
     - vault-volume:/root
     - .:/app/server
    env_file:
      - .env.server
volumes:
  vault-volume:
